[package]
name = "chirpstack_api_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chirpstack_api = "4.1.1"
http = "0.2.8"
thiserror = "1.0.31"
tonic = "0.8.2"